language: python
python:
  - "2.7"
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:boost-latest/ppa'
    packages:
      - gcc-5
      - g++-5
virtualenv:
  system_site_packages: false
env:
  - SIMPHONY_VERSION=master
  - SIMPHONY_VERSION=0.6.0
matrix:
    allow_failures:
        - env: SIMPHONY_VERSION=master
before_install:
  - sudo apt-get upgrade libstdc++6
  - wget https://github.com/KratosMultiphysics/Kratos/releases/download/v5.0-Simphony/kratos-simphony.tgz -O /tmp/kratos.tgz
  - mkdir $PWD/kratos
  - tar -xzvf /tmp/kratos.tgz -C $PWD/kratos
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/kratos/libs
  - export PYTHONPATH=$PYTHONPATH:$PWD/kratos
  - export PATH=$PATH:$PWD/kratos

install:
  - pip install -e git+https://github.com/simphony/simphony-common.git${SIMPHONY_REMOTE}#egg=simphony
  - pip install -r dev_requirements.txt
  - python setup.py develop

script:
  - flake8 . --ignore=E121,E123,E126,E226,E24,E704,W503,W504,F405,F401,F403
  - python2 -m unittest discover
