language: python
python:
  - "2.7"

before_install:
  - wget https://web.cimne.upc.edu/users/croig/data/kratos-4.4.11030-linux-64.tgz -O /tmp/kratos.tar.gz
  - tar -xzvf /tmp/kratos.tar.gz
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD:/kratos.gid/Kratos/kratos.gid/kratos/libs
  - export PYTHONPATH=$PYTHONPATH:$PWD:/kratos.gid/Kratos/kratos.gid/kratos/
  - export PATH=$PATH:$PWD:/kratos.gid/Kratos/kratos.gid/kratos/

install:
  - pip install -r dev_requirements.txt
  - python setup.py develop

script:
  - flake8 --exclude=use_cases,utilities,kratos.gid,ProjectParameters.py --ignore=F403 .
  - python -m unittest discover
