language: python
python:
  - "2.7"

before_install:
  - wget https://web.cimne.upc.edu/users/croig/data/kratos-simphony.tgz -O /tmp/kratos.tgz
  - mkdir $PWD/kratos
  - tar -xzvf /tmp/kratos.tgz -C $PWD/kratos
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/kratos/libs
  - export PYTHONPATH=$PYTHONPATH:$PWD/kratos
  - export PATH=$PATH:$PWD/kratos

install:
  - pip install -r dev_requirements.txt
  - python setup.py develop

script:
  - flake8 --exclude=use_cases,utilities,kratos.gid,ProjectParameters.py --ignore=F403 .
  - python -m unittest discover
